from django.shortcuts import render

# Create your views here.
from .sub_views.cruise_view import cruise_view
from.sub_views.home_page_view import home_page_view
from .sub_views.about_us import about_us
from.sub_views.history import history
from.sub_views.careers import careers
from.sub_views.blog import blog
from.sub_views.awards_achievements import awards_achievements
from.sub_views.group_tours import group_tours
from.sub_views.packages_india_view import packages_india_view
from.sub_views.packages_international_view import packages_international_view
from.sub_views.home_page_view import home_page_view
from.sub_views.wedding_goa_view import wedding_goa_view
from.sub_views.wedding_andaman_view import wedding_andaman_view
from.sub_views.wedding_india_view import wedding_india_view
from.sub_views.wedding_jaipur_view import wedding_jaipur_view
from.sub_views.wedding_agra_view import wedding_agra_view
from.sub_views.wedding_udaipur_view import wedding_udaipur_view
from.sub_views.wedding_jodpur_view import wedding_jodpur_view
from.sub_views.wedding_kerala_view import wedding_kerala_view
from.sub_views.wedding_jaisalmer_view import wedding_jaisalmer_view
from.sub_views.wedding_international_view import wedding_international_view